 # 系统配置
lihua:
  # 系统版本
  version: 1.2.1
  # 令牌过期时间（分钟）
  tokenExpireTime: 1440
  # 令牌刷新阈值（分钟）距令牌过期15分钟内时，有新请求时对令牌进行刷新
  refreshThreshold: 15
  # 附件下载生成链接过期时间（分钟）
  fileDownloadExpireTime: 30
  # 允许跨域的最长时间
  corsMaxAge: 3600
  # sse 过期时长（28800000 毫秒 8小时），超过连接时长前端在线情况会自动发起重连
  sseExpireTime: 28800000
  # 文件上传服务类型：LOCAL（传统本地上传）、MINIO（Minio对象存储）
  uploadFileModel: LOCAL
  # 公开文件的业务编码，publicLocalDownload 中判断包含业务编码的文件才会进行返回
  uploadPublicBusinessCode: [UserAvatar, SystemNotice]
  # 上传文件路径 mac windows 注意目录切换
  uploadFilePath: ${BASE_FILE_PATH}upload/
  # 文件导出路径
  exportFilePath: ${BASE_FILE_PATH}export/

# 处理因linux系统临时文件清理导致文件上传报错
server:
  tomcat:
    basedir: ${BASE_FILE_PATH}temp

# 数据源配置
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${DB_HOST}:${DB_PORT}/lihua
          username: ${DB_USERNAME}
          password: ${DB_PASSWORD}
          hikari:
            # 最大连接数默认 10
            maximum-pool-size: 20
            # 最小空闲连接 默认10
            minimum-idle: 5
            # 等待连接池连接最大时长（毫秒）
            connection-timeout: 5000
            # 空闲连接最大时长（毫秒）
            idle-timeout: 120000
            # 连接生命时长（毫秒）
            max-lifetime: 1800000
# 多数据源配置，使用dynamic-datasource实现，具体文档请参考：https://www.kancloud.cn/tracy5546/dynamic-datasource/2264611
#        slave_1:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/dynamic
#          username: root
#          password: 123456
#          hikari:
#            # 最大连接数默认 10
#            maximum-pool-size: 30
#            # 最小空闲连接 默认10
#            minimum-idle: 30
#            # 等待连接池连接最大时长（毫秒）
#            connection-timeout: 5000
#            # 空闲连接最大时长（毫秒）
#            idle-timeout: 0
#            # 连接生命时长（毫秒）
#            max-lifetime: 25800

  # redis配置
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      # 读取超时
      timeout: 3000
      # 连接超时
      connectTimeout: 5000
      # lettuce连接池
      lettuce:
        pool:
          # 最小空闲连接
          min-idle: 5
          # 最大空闲连接
          max-idle: 10
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000

# 日志配置
logging:
  file:
    name: ${BASE_FILE_PATH}logs/lihua.log
  level:
    com.lihua: debug
    org.springframework: info

xxl-job:
  # 是否启用定时任务
  enable: true
  # 调度中心部署地址
  adminAddress: http://${XXL_JOB_HOST}:${XXL_JOB_PORT}/xxl-job-admin
  # 执行器通讯token
  accessToken: default_token
  # 执行器应用名称
  appName: lihua
  # 执行器注册地址
  address:
  # 执行器ip
  ip:
  # 执行器端口号
  port: 0
  # 执行器日志保存目录
  logPath: ${BASE_FILE_PATH}job-logs
  # 执行器日志保存天数
  logRetentionDays: 30

 # minio 相关配置（若要启用minio需在lihua-uploadFileModel中设置值为MINIO）
minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: ${MINIO_BUCKET_NAME}

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
# 生产模式打开，防止接口泄漏
  production: true
  setting:
    language: zh_cn